name: sdg_test_task
description: "A test task for Social Discovery Group"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: 5.4.2+1
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  freezed_annotation: 2.4.1
  get_it: 7.6.8
  pretty_dio_logger: 1.3.1

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  golden_toolkit: 0.15.0
  mocktail: 1.0.3

flutter:
  uses-material-design: true
